//
//  Voices.swift
//  ReadSpeak
//
//  Created by Pranav Ramesh on 7/8/20.
//

import Foundation

let voiceISO = [
    "af",
    "sq",
    "ar-dz",
    "ar-bh",
    "ar-eg",
    "ar-iq",
    "ar-jo",
    "ar-kw",
    "ar-lb",
    "ar-ly",
    "ar-ma",
    "ar-om",
    "ar-qa",
    "ar-sa",
    "ar-sy",
    "ar-tn",
    "ar-ae",
    "ar-ye",
    "eu",
    "be",
    "bg",
    "ca",
    "zh-hk",
    "zh-cn",
    "zh-sg",
    "zh-tw",
    "hr",
    "cs",
    "da",
    "nl-be",
    "nl",
    "en",
    "en-au",
    "en-bz",
    "en-ca",
    "en-ie",
    "en-jm",
    "en-nz",
    "en-za",
    "en-tt",
    "en-gb",
    "en-us",
    "et",
    "fo",
    "fa",
    "fi",
    "fr-be",
    "fr-ca",
    "fr-lu",
    "fr",
    "fr-ch",
    "gd",
    "de-at",
    "de-li",
    "de-lu",
    "de",
    "de-ch",
    "el",
    "he",
    "hi",
    "hu",
    "is",
    "id",
    "ga",
    "it",
    "it-ch",
    "ja",
    "ko",
    "ko",
    "ku",
    "lv",
    "lt",
    "mk",
    "ml",
    "ms",
    "mt",
    "no",
    "nb",
    "nn",
    "pl",
    "pt-br",
    "pt",
    "pa",
    "rm",
    "ro",
    "ro-md",
    "ru",
    "ru-md",
    "sr",
    "sk",
    "sl",
    "sb",
    "es-ar",
    "es-bo",
    "es-cl",
    "es-co",
    "es-cr",
    "es-do",
    "es-ec",
    "es-sv",
    "es-gt",
    "es-hn",
    "es-mx",
    "es-ni",
    "es-pa",
    "es-py",
    "es-pe",
    "es-pr",
    "es",
    "es-uy",
    "es-ve",
    "sv",
    "sv-fi",
    "th",
    "ts",
    "tn",
    "tr",
    "uk",
    "ur",
    "ve",
    "vi",
    "cy",
    "xh",
    "ji",
    "zu"
]

let voiceName = [
    "Afrikaans",
    "Albanian",
    "Arabic (Algeria)",
    "Arabic (Bahrain)",
    "Arabic (Egypt)",
    "Arabic (Iraq)",
    "Arabic (Jordan)",
    "Arabic (Kuwait)",
    "Arabic (Lebanon)",
    "Arabic (Libya)",
    "Arabic (Morocco)",
    "Arabic (Oman)",
    "Arabic (Qatar)",
    "Arabic (Saudi Arabia)",
    "Arabic (Syria)",
    "Arabic (Tunisia)",
    "Arabic (U.A.E.)",
    "Arabic (Yemen)",
    "Basque",
    "Belarusian",
    "Bulgarian",
    "Catalan",
    "Chinese (Hong Kong)",
    "Chinese (PRC)",
    "Chinese (Singapore)",
    "Chinese (Taiwan)",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch (Belgium)",
    "Dutch (Standard)",
    "English",
    "English (Australia)",
    "English (Belize)",
    "English (Canada)",
    "English (Ireland)",
    "English (Jamaica)",
    "English (New Zealand)",
    "English (South Africa)",
    "English (Trinidad)",
    "English (United Kingdom)",
    "English (United States)",
    "Estonian",
    "Faeroese",
    "Farsi",
    "Finnish",
    "French (Belgium)",
    "French (Canada)",
    "French (Luxembourg)",
    "French (Standard)",
    "French (Switzerland)",
    "Gaelic (Scotland)",
    "German (Austria)",
    "German (Liechtenstein)",
    "German (Luxembourg)",
    "German (Standard)",
    "German (Switzerland)",
    "Greek",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Irish",
    "Italian (standard)",
    "Italian (Switzerland)",
    "Japanese",
    "Korean",
    "Korean (Johab)",
    "Kurdish",
    "Latvian",
    "Lithuanian",
    "Macedonian (FYROM)",
    "Malayalam",
    "Malaysian",
    "Maltese",
    "Norwegian",
    "Norwegian (Bokmål)",
    "Norwegian (Nynorsk)",
    "Polish",
    "Portuguese (Brazil)",
    "Portuguese (Portugal)",
    "Punjabi",
    "Rhaeto-Romanic",
    "Romanian",
    "Romanian (Republic of Moldova)",
    "Russian",
    "Russian (Republic of Moldova)",
    "Serbian",
    "Slovak",
    "Slovenian",
    "Sorbian",
    "Spanish (Argentina)",
    "Spanish (Bolivia)",
    "Spanish (Chile)",
    "Spanish (Colombia)",
    "Spanish (Costa Rica)",
    "Spanish (Dominican Republic)",
    "Spanish (Ecuador)",
    "Spanish (El Salvador)",
    "Spanish (Guatemala)",
    "Spanish (Honduras)",
    "Spanish (Mexico)",
    "Spanish (Nicaragua)",
    "Spanish (Panama)",
    "Spanish (Paraguay)",
    "Spanish (Peru)",
    "Spanish (Puerto Rico)",
    "Spanish (Spain)",
    "Spanish (Uruguay)",
    "Spanish (Venezuela)",
    "Swedish",
    "Swedish (Finland)",
    "Thai",
    "Tsonga",
    "Tswana",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Venda",
    "Vietnamese",
    "Welsh",
    "Xhosa",
    "Yiddish",
    "Zulu"
]
